### ISSUE TITLE
It sometimes crashes when player joins

### ISSUE THREAD

**Issue by andriycraft** [andriycraft/GreenFrogMCBE#1]

**Comment by BasToTheMax** [comment]
Could you provide more info? Like:

- Error logs
- OS
- minecraft version
ect

**Comment by MyrsujV2** [comment]
This was fixed in this pr: https://github.com/andriycraft/GreenFrogMCBE/pull/2
This was caused by packet reading issue

**Comment by andriycraft** [comment]
ok
