### ISSUE TITLE
Edit Form System

### ISSUE THREAD

**Issue by Zwuiix-cmd** [andriycraft/GreenFrogMCBE#35]
## What feature?

The features will allow to fully implement the forms, either form or custom_form, as well as the response of it.
I have already realized this code in my project, if you wish, I can allow you to greatly improve yours.

*I find it disastrous* 

![Issue](https://user-images.githubusercontent.com/71025924/216458777-579ef4dc-fe5d-412e-8b0d-091b8a1479bc.PNG)

My code:

![ModalFormRequestPacket_js](https://user-images.githubusercontent.com/71025924/216459979-656df985-53e9-4cd3-b84f-df1e600a8036.png)
![Player_js](https://user-images.githubusercontent.com/71025924/216459982-6a2e6633-18b4-456e-be65-68fb799d63cf.png)
![Form_js](https://user-images.githubusercontent.com/71025924/216459983-253086f5-d851-4c08-923b-8a66e4f2b7c7.png)
![FormID_js](https://user-images.githubusercontent.com/71025924/216459985-ab663fa8-d0f1-4c4d-a9be-d79a8b522590.png)
![CustomForm_js](https://user-images.githubusercontent.com/71025924/216459987-9067d4a3-c677-4555-a422-98e60e7c1b85.png)
![SimpleForm_js](https://user-images.githubusercontent.com/71025924/216459990-08412729-4268-477e-ace6-ca4965c73848.png)

Sincerely Zwuiix.

**Comment by AnyBananaGAME** [comment]
Very thanks 😊

**Comment by andriycraft** [comment]
I am working on this. It will be in 2.2 update

**Comment by Zwuiix-cmd** [comment]
I forgot to send you the response system!
![ModalFormResponsePacket_js](https://user-images.githubusercontent.com/71025924/216681796-e4ffc670-25f2-4277-a94a-357252bd6b34.png)

**Comment by andriycraft** [comment]
Currently I implemented a better form system. 

custom_form soon

**Comment by bufferfishq** [comment]
![image](https://user-images.githubusercontent.com/124588671/217185022-62bcf550-baf6-48f9-a5ab-694b040e0cd2.png)

**Comment by bufferfishq** [comment]
done
